---
services:
  app81:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: '8.1'
    environment: &env
      PHP_IDE_CONFIG: 'serverName=icanboogie-session'
    volumes: &vol
      - .:/app:delegated
      - ~/.composer:/root/.composer:delegated
    working_dir: /app
  app82:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: '8.2'
    environment: *env
    volumes: *vol
    working_dir: /app
  app83:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: '8.3'
    environment: *env
    volumes: *vol
    working_dir: /app
